---
- name: openvpn | Deploy temp openssl.conf
  template:
    src: "openssl_conf.j2"
    dest: "/tmp/openssl.conf"
    group: "root"
    owner: "root"
    mode: "0400"
  notify:
  - "Delete temp openssl.conf"
- name: openvpn | Revoke target cert
  shell: "{{ 'openssl ca -config /tmp/openssl.conf -keyfile ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootkey'] ~ ' -cert ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootcrt'] ~ ' -revoke ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_revoke_target'] ~ '.crt' }}"
- name: openvpn | Generate CRL
  shell: "{{ 'openssl ca -config /tmp/openssl.conf -keyfile ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootkey'] ~ ' -cert ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootcrt'] ~ ' -gencrl -out ' ~
    vars['openvpn_ca_settings']['crl_path'] ~ '/' ~
    vars['openvpn_ca_settings']['crl_file'] }}"
- name: openvpn | Delete revoked cert
  file:
    path: "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
      vars['openvpn_revoke_target'] ~ item }}"
    state: "absent"
  loop:
  - '.csr'
  - '.crt'
  - '.key'
  loop_control:
    label: "{{ vars['openvpn_revoke_target'] ~ item }}"
- name: openvpn | Fetch CRL from master
  fetch:
    src: "{{ vars['openvpn_ca_settings']['crl_path'] ~ '/' ~
      vars['openvpn_ca_settings']['crl_file'] }}"
    dest: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' }}"
    flat: "yes"
    validate_checksum: "yes"
    fail_on_missing: "yes"
