---
- name: openvpn | Copy TLS files for client instance
  copy:
    src: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' ~ item }}"
    dest: "{{ hostvars[inventory_hostname]['openvpn_client_conf_dest'] ~ '/' ~
      vars['outer_item'].name ~ '/tls' }}"
    group: "{{ vars['openvpn_env_settings']['group'] | default('root') }}"
    owner: "{{ vars['openvpn_env_settings']['user'] | default('root') }}"
    mode: "0400"
  loop:
  - "{{ vars['openvpn_instance_name'] ~ '.crt' }}"
  - "{{ vars['openvpn_instance_name'] ~ '.key' }}"
  - "{{ vars['openvpn_ca_settings']['file'] }}"
  - "{{ vars['openvpn_env_settings']['takey_file'] }}"
  diff: "false"
  notify:
  - "Delete fetched files"
  when:
  - "vars['outer_item'].type == 'client'"
- name: openvpn | Copy TLS files for server instance
  copy:
    src: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' ~ item }}"
    dest: "{{ hostvars[inventory_hostname]['openvpn_server_conf_dest'] ~ '/' ~
      vars['outer_item'].name ~ '/tls' }}"
    group: "{{ vars['openvpn_env_settings']['group'] | default('root') }}"
    owner: "{{ vars['openvpn_env_settings']['user'] | default('root') }}"
    mode: "0400"
  loop:
  - "{{ vars['openvpn_instance_name'] ~ '.crt' }}"
  - "{{ vars['openvpn_instance_name'] ~ '.key' }}"
  - "{{ vars['openvpn_ca_settings']['file'] }}"
  - "{{ vars['openvpn_env_settings']['takey_file'] }}"
  - "{{ vars['openvpn_env_settings']['dhparam_file'] }}"
  - "{{ vars['openvpn_ca_settings']['crl_file'] }}"
  diff: "false"
  notify:
  - "Delete fetched files"
  when:
  - "vars['outer_item'].type == 'server'"
