---
- name: openvpn | Check availability key on master
  stat:
    path: "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
      vars['openvpn_revoke_target'] ~ '.crt' }}"
  register: "openvpn_cert_result"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Assert that revoke target is exists
  assert:
    that:
    - "openvpn_cert_result.stat.exists == True"
    msg: "{{ 'Cert for ' ~ vars['openvpn_revoke_target'] ~ ' not found' }}"
- name: openvpn | Deploy temp openssl.conf
  template:
    src: "openssl_conf.j2"
    dest: "/tmp/openssl.conf"
    group: "root"
    owner: "root"
    mode: "0400"
  notify:
  - "Delete temp openssl.conf"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Revoke target cert
  shell: "{{ 'openssl ca -config /tmp/openssl.conf -keyfile ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootkey'] ~ ' -cert ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootcrt'] ~ ' -revoke ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_revoke_target'] ~ '.crt' }}"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Generate CRL
  shell: "{{ 'openssl ca -config /tmp/openssl.conf -keyfile ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootkey'] ~ ' -cert ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootcrt'] ~ ' -gencrl -out ' ~
    vars['openvpn_ca_settings']['crl_path'] ~ '/' ~
    vars['openvpn_ca_settings']['crl_file'] }}"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Delete revoked cert
  file:
    path: "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
      vars['openvpn_revoke_target'] ~ item }}"
    state: "absent"
  loop:
  - '.csr'
  - '.crt'
  - '.key'
  loop_control:
    label: "{{ vars['openvpn_revoke_target'] ~ item }}"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Fetch CRL from master
  fetch:
    src: "{{ vars['openvpn_ca_settings']['crl_path'] ~ '/' ~
      vars['openvpn_ca_settings']['crl_file'] }}"
    dest: "{{ vars['local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' }}"
    flat: "yes"
    validate_checksum: "yes"
    fail_on_missing: "yes"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Update CRL
  copy:
    src: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_ca_settings']['crl_file'] }}"
    dest: "{{ vars['openvpn_env_settings']['tls_dest'] }}"
    group: "{{ vars['openvpn_env_settings']['group'] }}"
    owner: "{{ vars['openvpn_env_settings']['user'] }}"
    mode: "0400"
  notify:
  - "Delete fetched files"
