---
- name: Make archive
  local_action: shell 7z a {{ fetch_dir }}{{ openvpn_instance_name }}/{{ openvpn_instance_name }}.7z {{ fetch_dir }}{{ openvpn_instance_name }}
  register: 'openvpn_archive_result'
  notify: 'Delete fetched files'
- name: Send mail
  local_action: mail
                host='{{ openvpn_mail_host }}'
                port='{{ openvpn_mail_port }}'
                username='{{ openvpn_mail_username }}'
                password='{{ openvpn_mail_password }}'
                subject='{{ openvpn_mail_subject }}'
                from='{{ openvpn_mail_from }}'
                headers='{{ openvpn_mail_headers }}'
                charset='{{ openvpn_mail_charset }}'
                body='{{ openvpn_mail_body }}'
                to='{{ openvpn_ldap_result.stdout }}'
                attach='{{ fetch_dir }}{{ openvpn_instance_name }}/{{ openvpn_instance_name }}.7z'
  when: 'openvpn_archive_result|success'
  register: 'openvpn_mail_result'
