---
- name: openvpn | Make archive
  local_action:
    module: "archive"
    path: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] }}"
    dest: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_instance_name'] ~ '.gz' }}"
  notify:
  - "Delete fetched files"
- name: openvpn | Send mail
  local_action:
    module: "mail"
    attach: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ vars['openvpn_instance_name'] ~ '.gz' }}"
    body: "{{ hostvars[inventory_hostname]['openvpn_mail_body'] |
      default(omit) }}"
    charset: "{{ hostvars[inventory_hostname]['openvpn_mail_charset'] |
      default(omit) }}"
    from: "{{ hostvars[inventory_hostname]['openvpn_mail_from'] |
      default(omit) }}"
    headers: "{{ hostvars[inventory_hostname]['openvpn_mail_headers'] |
      default(omit) }}"
    host: "{{ hostvars[inventory_hostname]['openvpn_mail_host'] |
      default(omit) }}"
    password: "{{ hostvars[inventory_hostname]['openvpn_mail_password'] |
      default(omit) }}"
    port: "{{ hostvars[inventory_hostname]['openvpn_mail_port'] |
      default(omit) }}"
    subject: "{{ hostvars[inventory_hostname]['openvpn_mail_subject'] |
      default(omit) }}"
    timeout: "{{ hostvars[inventory_hostname]['openvpn_mail_timeout'] |
      default(omit) }}"
    to: "{{ vars['openvpn_ldap_user_mail'] }}"
    username: "{{ hostvars[inventory_hostname]['openvpn_mail_username'] |
      default(omit) }}"
