---
- import_tasks: "pre_requisite.yml"
- import_tasks: 'packages.yml'
- import_tasks: "openvpn_ca.yml"
  when:
  - "vars['openvpn_instances_types_bool'] is defined"
  - "vars['openvpn_instances_types_bool'] == True"
- import_tasks: "openvpn_executor.yml"
  when:
  - "vars['openvpn_instances_types_bool'] is defined"
  - "vars['openvpn_instances_types_bool'] == True"
- include_tasks: "worker_user.yml"
  loop: "{{ vars['openvpn_instances'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "openvpn_fetching_type"
  when:
  - "openvpn_fetching_type.type == 'user'"
- name: openvpn | Set facts about end-user instance
  set_fact:
    openvpn_instance_name: "{{ vars['openvpn_target_user'] }}"
  loop: "{{ vars['openvpn_instances'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "openvpn_fetching_type"
  when:
  - "openvpn_fetching_type.type == 'user'"
- include_tasks: "userfind.yml"
  loop: "{{ vars['openvpn_instances'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "openvpn_fetching_type"
  when:
  - "openvpn_fetching_type.type == 'user'"
- include_tasks: "crl.yml"
  loop: "{{ vars['openvpn_instances'] | flatten(levels=1) }}"
  loop_control:
    loop_var: "openvpn_fetching_type"
  when:
  - "(vars['openvpn_revoke_target'] is defined and
      vars['openvpn_revoke_target'] != '')"
  - "openvpn_fetching_type.type == 'server'"
