---
- assert:
    that:
    - "hostvars[inventory_hostname]['openvpn_scenario'] is defined"
    - "hostvars[inventory_hostname]['openvpn_scenario'] in ['deploy_user',
      'deploy_instance', 'crl']"
    msg: "'openvpn_scenario' is undefined or have unknown value."
- assert:
    that:
    - "hostvars[inventory_hostname]['openvpn'] is defined"
    - "hostvars[inventory_hostname]['openvpn'] != []"
    msg: "'openvpn' settings is not defined or empty."
- import_tasks: "scenarios.d/openvpn_deploy_instance.yml"
  when:
  - "hostvars[inventory_hostname]['openvpn_scenario'] == 'deploy_instance'"
- import_tasks: "scenarios.d/openvpn_deploy_user.yml"
  when:
  - "hostvars[inventory_hostname]['openvpn_scenario'] == 'deploy_user'"
