---
- import_tasks: "pre_requisite.yml"
- include_tasks: "packages_ca_master.yml"
  when:
  - "vars['openvpn_revoke_target'] is not defined"
- include_tasks: "packages_client.yml"
  when:
  - "hostvars[inventory_hostname]['openvpn'] is defined"
  - "hostvars[inventory_hostname]['openvpn'] != ''"
  - "hostvars[inventory_hostname]['openvpn'] |
     json_query(vars['openvpn_install_package']) is defined"
  - "hostvars[inventory_hostname]['openvpn'] |
     json_query(vars['openvpn_install_package']) == 'true'"
  - "vars['openvpn_instance'] == 'client'"
  vars:
    openvpn_install_package: "[] | map(&install_package || 'false', @) | [0]"
- include_tasks: "master.yml"
  when:
  - "vars['openvpn_revoke_target'] is not defined"
  - "vars['openvpn_instance'] in ['server', 'client']"
- name: openvpn | Set facts about end-user instance
  set_fact:
    openvpn_instance_name: "{{ vars['openvpn_target_user'] }}"
  when:
  - "vars['openvpn_instance'] is defined"
  - "vars['openvpn_instance'] == 'user'"
- include_tasks: "userfind.yml"
  when:
  - "vars['openvpn_instance'] is defined"
  - "vars['openvpn_instance'] == 'user'"
- include_tasks: "crl.yml"
  when:
  - "(vars['openvpn_revoke_target'] is defined and
      vars['openvpn_revoke_target'] != '')"
  - "(vars['openvpn_instance'] is defined and
      vars['openvpn_instance'] == 'server')"
