---
- import_tasks: "pre_requisite.yml"
- include_tasks: "packages_ca_master.yml"
  when:
  - "vars['openvpn_revoke_target'] is not defined"
- include_tasks: "packages_client.yml"
  when:
  - "hostvars[inventory_hostname]['openvpn_install_packages'] is defined"
  - "hostvars[inventory_hostname]['openvpn_install_packages'] == 'true'"
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'client'"
- include_tasks: "master.yml"
  when:
  - "vars['openvpn_revoke_target'] is not defined"
  - "(hostvars[inventory_hostname]['openvpn_instance'] == 'client' or
      hostvars[inventory_hostname]['openvpn_instance'] == 'server')"
- name: openvpn | Set facts about end-user instance
  set_fact:
    openvpn_instance_name: "{{ vars['openvpn_target_user'] }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] is defined"
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'user'"
- include_tasks: "userfind.yml"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] is defined"
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'user'"
- include_tasks: "crl.yml"
  when:
  - "vars['openvpn_revoke_target'] is defined"
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'server'"
