---
- name: Check availability key on master
  stat:
    path: "{{ hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.crt' }}"
  register: "stat_result"
  delegate_to: "{{ hostvars[inventory_hostname]['ca_master'] }}"
- name: Generate cert on master
  shell: "{{ item }}"
  with_items:
   - "{{ 'openssl genrsa -out ' + hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.key' + ' 4096' }}"
   - "{{ 'openssl req -new -key ' + hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.key' + ' -subj ' + hostvars[inventory_hostname]['ca_subj'] + vars['openvpn_instance_name'] + ' -out ' + hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.csr' }}"
   - "{{ 'openssl x509 -req -in ' + hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.csr' + ' -CA ' + hostvars[inventory_hostname]['ca_path'] + hostvars[inventory_hostname]['ca_rootcrt'] + ' -CAkey ' + hostvars[inventory_hostname]['ca_path'] + hostvars[inventory_hostname]['ca_rootkey'] + ' -CAcreateserial -out ' + hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.crt' + ' -days 5000' }}"
  when: "stat_result.stat.exists == False"
  delegate_to: "{{ hostvars[inventory_hostname]['ca_master'] }}"
- name: Fetch cert from master
  fetch:
    src: "{{ item }}"
    dest: "{{ vars['local_fetch_dir'] + '/' + vars['openvpn_instance_name'] + '/' }}"
    flat: "yes"
    validate_checksum: "yes"
    fail_on_missing: "no"
  with_items:
   - "{{ hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.key' }}"
   - "{{ hostvars[inventory_hostname]['ca_path'] + vars['openvpn_instance_name'] + '.crt' }}"
   - "{{ hostvars[inventory_hostname]['ca_path'] + hostvars[inventory_hostname]['openvpn_ca_file'] }}"
   - "{{ hostvars[inventory_hostname]['ca_path'] + hostvars[inventory_hostname]['openvpn_src'] + '/' + hostvars[inventory_hostname]['openvpn_takey_file'] }}"
  delegate_to: "{{ hostvars[inventory_hostname]['ca_master'] }}"
  register: "openvpn_fetched_result_0"
- name: Fetch CRL and DHPARAM from master
  fetch:
    src: "{{ item }}"
    dest: "{{ vars['local_fetch_dir'] + '/' + vars['openvpn_instance_name'] + '/' }}"
    flat: "yes"
    validate_checksum: "yes"
    fail_on_missing: "no"
  with_items:
   - "{{ hostvars[inventory_hostname]['ca_path'] + hostvars[inventory_hostname]['openvpn_src'] + '/' + hostvars[inventory_hostname]['openvpn_dhparam_file'] }}"
   - "{{ hostvars[inventory_hostname]['ca_crl_path'] + hostvars[inventory_hostname]['openvpn_crl_file'] }}"
  delegate_to: "{{ hostvars[inventory_hostname]['ca_master'] }}"
  register: "openvpn_fetched_result_1"
  when: "hostvars[inventory_hostname]['openvpn_instance'] == 'server'"
- include: prepare.yml
  when: "openvpn_fetched_result_0|success and openvpn_fetched_result_1|success and hostvars[inventory_hostname]['openvpn_instance'] == 'server'"
- include: prepare.yml
  when: "openvpn_fetched_result_0|success and hostvars[inventory_hostname]['openvpn_instance'] == 'client'"
- include: worker.yml
  when: "openvpn_fetched_result_0|success and hostvars[inventory_hostname]['openvpn_instance'] == 'user'"
