---
- name: openvpn | Install the required packages in Redhat derivatives (CA)
  yum:
    name: "{{ vars['local_packages_master'] }}"
    state: "installed"
  when:
  - "vars['local_ca_master_os'] == 'RedHat'"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Install the required packages in Debian derivatives (CA)
  apt:
    name: "{{ vars['local_packages_master'] }}"
    state: "installed"
    update_cache: "yes"
  when:
  - "vars['local_ca_master_os'] == 'Debian'"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
- name: openvpn | Install the required packages in ArchLinux derivatives (CA)
  pacman:
    name: "{{ vars['local_packages_master'] }}"
    state: "installed"
    update_cache: "yes"
  when:
  - "vars['local_ca_master_os'] == 'Archlinux'"
  delegate_to: "{{ vars['openvpn_ca_settings']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_settings']['delegate_user'] }}"
