---
- include_tasks: 'prereq.d/openvpn_prereq_facts.yml'
- include_tasks: 'prereq.d/openvpn_prereq_filestore_delegation_host.yml'
  when:
  - "vars['openvpn_instances_types_bool'] is defined"
  - "vars['openvpn_instances_types_bool'] == True"
  - "vars['openvpn_ca_storage_type'] is defined"
  - "vars['openvpn_ca_storage_type'] == 'file'"
  run_once: "true"
- include_tasks: 'prereq.d/openvpn_prereq_instance_facts.yml'
  when:
  - "vars['openvpn_instances_types_bool'] is defined"
  - "vars['openvpn_instances_types_bool'] == True"
- include_tasks: 'prereq.d/openvpn_prereq_create_catalogs.yml'
  when:
  - "vars['openvpn_instances_types_bool'] is defined"
  - "vars['openvpn_instances_types_bool'] == True"
