---
- name: openvpn | Delete catalogs (clean up before deploy)
  file:
    name: "{{ item }}"
    state: "absent"
  loop:
  - "{{ hostvars[inventory_hostname]['openvpn_dest'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_tls_dest'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_log_dest'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_pool_dest'] }}"
- name: openvpn | Create catalogs
  file:
    path: "{{ item }}"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"
    recurse: "yes"
  loop:
  - "{{ hostvars[inventory_hostname]['openvpn_dest'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_tls_dest'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_log_dest'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_pool_dest'] }}"
- name: openvpn | Create client config catalogs
  file:
    path: "{{ item.client_config_dir }}"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"
    recurse: "yes"
  loop: "{{ hostvars[inventory_hostname]['openvpn_server'] }}"
  loop_control:
    label: "{{ item.client_config_dir }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'server'"
  - "item.client_config_dir is defined"
  - "item.client_config_dir != ''"
- name: openvpn | Copy TLS files for client instance
  copy:
    src: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ item }}"
    dest: "{{ hostvars[inventory_hostname]['openvpn_tls_dest'] }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_instance_group'] }}"
    owner: "{{ hostvars[inventory_hostname]['openvpn_instance_user'] }}"
    mode: "0400"
  loop:
  - "{{ hostvars[inventory_hostname]['openvpn_instance_name'] ~ '.crt' }}"
  - "{{ hostvars[inventory_hostname]['openvpn_instance_name'] ~ '.key' }}"
  - "{{ hostvars[inventory_hostname]['openvpn_ca_file'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_takey_file'] }}"
  diff: "false"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'client'"
- name: openvpn | Copy TLS files for server instance
  copy:
    src: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '/' ~ item }}"
    dest: "{{ hostvars[inventory_hostname]['openvpn_tls_dest'] }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_instance_group'] }}"
    owner: "{{ hostvars[inventory_hostname]['openvpn_instance_user'] }}"
    mode: "0400"
  loop:
  - "{{ hostvars[inventory_hostname]['openvpn_instance_name'] ~ '.crt' }}"
  - "{{ hostvars[inventory_hostname]['openvpn_instance_name'] ~ '.key' }}"
  - "{{ hostvars[inventory_hostname]['openvpn_ca_file'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_takey_file'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_dhparam_file'] }}"
  - "{{ hostvars[inventory_hostname]['openvpn_ca_crl_file'] }}"
  diff: "false"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'server'"
- import_tasks: "worker.yml"
