---
- name: openvpn | Deploy client configuration
  template:
    src: "openvpn_client.j2"
    dest: "{{ hostvars[inventory_hostname]['openvpn_dest'] ~ '/' ~
              item.name ~ '.conf' }}"
    group: "root"
    owner: "root"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_client'] }}"
  loop_control:
    label: "{{ item.name ~ '.conf' }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'client'"
- name: openvpn | Deploy server configuration
  template:
    src: "openvpn_server.j2"
    dest: "{{ hostvars[inventory_hostname]['openvpn_dest'] ~ '/' ~
              item.name ~ '.conf' }}"
    group: "root"
    owner: "root"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_server'] }}"
  loop_control:
    label: "{{ item.name ~ '.conf' }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'server'"
  notify:
  - "Deploy plugin configuration"
  - "Deploy clients configuration"
- name: openvpn | Deploy user configuration
  local_action:
    module: "template"
    src: "openvpn_client.j2"
    dest: "{{ vars['local_fetch_dir'] ~ '/' ~ vars['openvpn_instance_name'] ~
              '/' ~ vars['openvpn_instance_name'] ~ '.conf' }}"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_client'] }}"
  loop_control:
    label: "{{ vars['openvpn_instance_name'] ~ '.conf' }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'user'"
- include_tasks: mail.yml
  when:
  - "hostvars[inventory_hostname]['openvpn_instance'] == 'user'"
