---
- name: Deploy config
  template: src='openvpn_{{ openvpn_instance }}.j2' dest='{{ openvpn_dest }}{{ item.name }}.conf' group='root' owner='root' mode='0644'
  with_items: 'openvpn_{{ openvpn_instance }}'
  register: 'openvpn_deploy_result'
  when: "openvpn_instance == 'server' or openvpn_instance == 'client'"
  notify: 'Deploy server configuration'
- name: Deploy user configuration
  local_action: template src='openvpn_client.j2'
    dest='{{ fetch_dir }}{{ openvpn_instance_name }}/{{ openvpn_instance_name }}.conf'
    mode='0644'
  with_items: 'openvpn_client'
  register: 'openvpn_local_result'
  when: "openvpn_instance == 'user'"
- include: mail.yml
  when: "openvpn_local_result|success and openvpn_instance == 'user'"
  