---
- include_tasks: "worker_client.yml"
  when:
  - "vars['openvpn_instance'] == 'client'"
- include_tasks: "worker_server.yml"
  when:
  - "vars['openvpn_instance'] == 'server'"
- include_tasks: "worker_user.yml"
  when:
  - "vars['openvpn_instance'] == 'user'"
