---
- name: openvpn | Generate private key on CA (filestore)
  openssl_privatekey:
    type: "RSA"
    path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.key' }}"
- name: openvpn | Generate certificate signing request on CA (filestore)
  openssl_csr:
    common_name: "{{ vars['openvpn_instance_name'] }}"
    country_name: "{{ vars['openvpn_csr_settings']['country_name'] |
      default(omit) }}"
    state_or_province_name: "{{
      vars['openvpn_csr_settings']['openvpn_csr_state'] | default(omit) }}"
    locality_name: "{{ vars['openvpn_csr_settings']['locality_name'] |
      default(omit) }}"
    organization_name: "{{ vars['openvpn_csr_settings']['organization_name'] |
      default(omit) }}"
    organizational_unit_name: "{{
      vars['openvpn_csr_settings']['organization_unit'] | default(omit) }}"
    path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.csr' }}"
    privatekey_path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.key' }}"
- name: openvpn | Generate certificate on CA (filestore)
  openssl_certificate:
    csr_path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.csr' }}"
    ownca_path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_ca_storage_source']['root_crt'] }}"
    ownca_privatekey_path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~
      '/' ~ vars['openvpn_ca_storage_source']['root_key'] }}"
    path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.crt' }}"
    privatekey_path: "{{ vars['openvpn_ca_storage_source']['root_path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.key' }}"
    provider: "ownca"
