---
- name: Delete fetched files
  local_action: file
                path="{{ vars['local_fetch_dir'] }}"
                state="absent"
- name: Deploy plugin configuration
  template:
    src: "auth_ldap.j2"
    dest: "{{ hostvars[inventory_hostname]['openvpn_dest'] + item.plugin_conf }}"
    group: "{{ item.group }}"
    owner: "{{ item.user }}"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_server'] }}"
  when: "item.plugin is defined and item.plugin == 'true'"
- name: Deploy clients configuration
  template:
    src: "client_config_dir.j2"
    dest: "{{ item.dest + '/' + item.cn }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_instance_group'] }}"
    owner: "{{ hostvars[inventory_hostname]['openvpn_instance_user'] }}"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_clients_conf'] }}"
  when: "hostvars[inventory_hostname]['openvpn_client_config_mgmt'] is defined and hostvars[inventory_hostname]['openvpn_client_config_mgmt'] != ''"
