---
- name: Delete fetched files
  file:
    path: "{{ vars['openvpn_local_fetch_dir'] }}"
    state: "absent"
  become: "false"
  delegate_to: "localhost"
- name: Delete temp openssl.conf
  file:
    path: "/tmp/openssl.conf"
    state: "absent"
  delegate_to: "{{ vars['openvpn_ca_storage_source']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_storage_source']['delegate_user'] }}"
- name: Restart OpenVPN
  systemd:
    name: "{{ hostvars[inventory_hostname]['openvpn_' ~ item.type ~
      '_service'] ~ item.name }}"
    state: "restarted"
  loop: "{{ vars['openvpn_instances'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ 'openvpn-' ~ item.type ~ ': ' ~ item.name }}"
  when:
  - "hostvars[inventory_hostname]['openvpn'] is defined"
  - "hostvars[inventory_hostname]['openvpn'] != ''"
  - "hostvars[inventory_hostname]['openvpn'] |
     json_query(vars['openvpn_restart']) is defined"
  - "hostvars[inventory_hostname]['openvpn'] |
     json_query(vars['openvpn_restart']) == 'true'"
  - "item.name != None"
  vars:
    openvpn_restart: "[] | map(&restart || 'false', @) | [0]"
