---
- name: Delete fetched files
  local_action:
    module: "file"
    path: "{{ vars['local_fetch_dir'] }}"
    state: "absent"
- name: Delete temp openssl.conf
  file:
    path: "/tmp/openssl.conf"
    state: "absent"
  delegate_to: "{{ hostvars[inventory_hostname]['openvpn_ca_master'] }}"
- name: Deploy plugin configuration
  template:
    src: "auth_ldap.j2"
    dest: "{{ hostvars[inventory_hostname]['openvpn_dest'] ~ '/' ~
              item.plugin_conf }}"
    group: "{{ item.group }}"
    owner: "{{ item.user }}"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_server'] }}"
  loop_control:
    label: "{{ item.plugin }}"
  when:
  - "item.plugin is defined"
  - "item.plugin == 'true'"
- name: Deploy clients configuration
  template:
    src: "client_config_dir.j2"
    dest: "{{ item.dest + '/' + item.cn }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_instance_group'] }}"
    owner: "{{ hostvars[inventory_hostname]['openvpn_instance_user'] }}"
    mode: "0400"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_clients_conf'] }}"
  loop_control:
    label: "{{ item.cn }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_client_config_mgmt'] is defined"
  - "hostvars[inventory_hostname]['openvpn_client_config_mgmt'] != ''"
- name: Restart openvpn-client instances
  systemd:
    name: "{{
      hostvars[inventory_hostname]['openvpn_client_service'] ~ item.name }}"
    state: "restarted"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_client'] }}"
  loop_control:
    label: "{{
      hostvars[inventory_hostname]['openvpn_client_service'] ~ item.name }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_client_restart'] is defined"
  - "hostvars[inventory_hostname]['openvpn_client_restart'] == 'true'"
- name: Restart openvpn-server instances
  systemd:
    name: "{{
      hostvars[inventory_hostname]['openvpn_server_service'] ~ item.name }}"
    state: "restarted"
  with_items: "{{ hostvars[inventory_hostname]['openvpn_server'] }}"
  loop_control:
    label: "{{
      hostvars[inventory_hostname]['openvpn_server_service'] ~ item.name }}"
  when:
  - "hostvars[inventory_hostname]['openvpn_server_restart'] is defined"
  - "hostvars[inventory_hostname]['openvpn_server_restart'] == 'true'"
