---
- name: openvpn | Deploy OpenVPN user configuration
  template:
    src: "openvpn_conf.j2"
    dest: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '.conf' }}"
    mode: "0400"
  loop: "{{ hostvars[inventory_hostname]['openvpn'] |
    json_query('[].openvpn_settings[]') | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.name }}"
- name: openvpn | Deploy OpenVPN user configuration (OVPN Profile)
  template:
    src: "openvpn_conf.j2"
    dest: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' ~ vars['openvpn_instance_name'] ~
      '.ovpn' }}"
    mode: "0400"
  loop: "{{ hostvars[inventory_hostname]['openvpn'] |
    json_query('[].openvpn_settings[]') | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.name }}"
  vars:
    openvpn_inline_profile: "true"
