---
- name: openvpn | Set LDAP facts
  set_fact:
    ldap_lookup_config:
      url: "{{ vars['openvpn_ldap_settings']['host'] }}"
      base: "{{ vars['openvpn_ldap_settings']['basedn'] }}"
      binddn: "{{ vars['openvpn_ldap_settings']['binddn'] }}"
      bindpw: "{{ vars['openvpn_ldap_settings']['password'] }}"
      scope: 'subtree'
      filter: "{{ '(' ~ vars['openvpn_ldap_settings']['filter'] ~ '=' ~
        vars['openvpn_instance_name'] ~ ')' }}"
    openvpn_mailaddr_regex: '^[a-zA-Z0-9.!#$%&*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
- name: openvpn | Get user mail address
  set_fact:
    openvpn_ldap_user_mail: "{{ item }}"
  with_ldap:
  - value:
    - "{{ vars['openvpn_ldap_settings']['mail_field'] }}"
- name: openvpn | Check user is present on LDAP
  assert:
    that:
    - "vars['openvpn_ldap_user_mail'] is defined"
    msg: "{{ 'User' ~ ' ' ~ vars['openvpn_instance_name'] ~ ' ' ~
             'not found' }}"
    quiet: "true"
- name: openvpn | Check user mail is valid e-mail address
  assert:
    that:
    - "vars['openvpn_ldap_user_mail'] is match(vars['openvpn_mailaddr_regex'])"
    msg: "{{ 'User' ~ ' ' ~ vars['openvpn_instance_name'] ~ ' ' ~
             'mail address not found' }}"
    quiet: "true"
