---
- name: openvpn | Generate private key on master
  openssl_privatekey:
    type: "RSA"
    path: "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.key' }}"
- name: openvpn | Generate certificate signing request on master
  openssl_csr:
    common_name: "{{ vars['openvpn_instance_name'] }}"
    country_name: "{{ vars['openvpn_csr_settings']['country_name'] |
      default(omit) }}"
    state_or_province_name: "{{
      vars['openvpn_csr_settings']['openvpn_csr_state'] | default(omit) }}"
    locality_name: "{{ vars['openvpn_csr_settings']['locality_name'] |
      default(omit) }}"
    organization_name: "{{ vars['openvpn_csr_settings']['organization_name'] |
      default(omit) }}"
    organizational_unit_name: "{{
      vars['openvpn_csr_settings']['organization_unit'] | default(omit) }}"
    path: "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.csr' }}"
    privatekey_path: "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '.key' }}"
- name: openvpn | Generate certificate on master
  shell: "{{ 'openssl x509 -req -in ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_instance_name'] ~ '.csr' ~ ' -CA ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootcrt'] ~ ' -CAkey ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_ca_settings']['rootkey'] ~ ' -CAcreateserial -out ' ~
    vars['openvpn_ca_settings']['path'] ~ '/' ~
    vars['openvpn_instance_name'] ~ '.crt' ~ ' -days 5000' }}"
