---
- name: openvpn | Fetch cert from master
  fetch:
    src: "{{ openvpn_fetching }}"
    dest: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' }}"
    flat: "yes"
    validate_checksum: "yes"
    fail_on_missing: "no"
  loop:
  - "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
        vars['openvpn_instance_name'] ~ '.key' }}"
  - "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
        vars['openvpn_instance_name'] ~ '.crt' }}"
  - "{{ vars['openvpn_ca_settings']['path'] ~ '/' ~
        vars['openvpn_ca_settings']['file'] }}"
  - "{{ vars['openvpn_env_settings']['src'] ~ '/' ~
        vars['openvpn_env_settings']['takey_file'] }}"
  loop_control:
    loop_var: "openvpn_fetching"
- name: openvpn | Fetch CRL and DHPARAM from master
  fetch:
    src: "{{ openvpn_fetching }}"
    dest: "{{ vars['openvpn_local_fetch_dir'] ~ '/' ~
      vars['openvpn_instance_name'] ~ '/' }}"
    flat: "yes"
    validate_checksum: "yes"
    fail_on_missing: "no"
  loop:
  - "{{ vars['openvpn_env_settings']['src'] ~ '/' ~
        vars['openvpn_env_settings']['dhparam_file'] }}"
  - "{{ vars['openvpn_ca_settings']['crl_path'] ~ '/' ~
        vars['openvpn_ca_settings']['crl_file'] }}"
  loop_control:
    loop_var: "openvpn_fetching"
  when:
  - "vars['openvpn_fetching_type'].type == 'server'"
