---
- name: openvpn | Install the required packages in Redhat derivatives (CA)
  yum:
    name: "{{ vars['local_packages_master'] }}"
    state: "installed"
  when:
  - "vars['local_ca_master_os'] == 'RedHat'"
- name: openvpn | Install the required packages in Debian derivatives (CA)
  apt:
    name: "{{ vars['local_packages_master'] }}"
    state: "installed"
    update_cache: "yes"
  when:
  - "vars['local_ca_master_os'] == 'Debian'"
- name: openvpn | Install the required packages in ArchLinux derivatives (CA)
  pacman:
    name: "{{ vars['local_packages_master'] }}"
    state: "installed"
    update_cache: "yes"
  when:
  - "vars['local_ca_master_os'] == 'Archlinux'"
