---
- name: openvpn | Install the required packages in Redhat derivatives
  block:
  - name: openvpn | Install the required packages for RedHat via yum
    ansible.builtin.yum:
      name: "{{ vars['local_packages_master'] }}"
      state: "present"
      update_cache: "yes"
    when:
      - "vars['local_ca_master_pkg_mgr'] == 'yum'"
  - name: openvpn | Install the required packages for RedHat via dnf
    ansible.builtin.dnf:
      name: "{{ vars['local_packages_master'] }}"
      state: "present"
      update_cache: "yes"
    when:
      - "vars['local_ca_master_pkg_mgr'] == 'dnf'"
  when:
    - "vars['local_ca_master_os'] == 'RedHat'"
- name: openvpn | Install the required packages in Debian derivatives (CA)
  ansible.builtin.apt:
    name: "{{ vars['local_packages_master'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "vars['local_ca_master_os'] == 'Debian'"
- name: openvpn | Install the required packages in ArchLinux derivatives (CA)
  community.general.pacman:
    name: "{{ vars['local_packages_master'] }}"
    state: "present"
    update_cache: "yes"
  when:
    - "vars['local_ca_master_os'] == 'Archlinux'"
