---
- name: openvpn | Create client config catalogs
  file:
    path: "{{ hostvars[inventory_hostname]['openvpn_server_conf_dest'] ~ '/' ~
      vars['outer_item'].name }}"
    state: "directory"
    owner: "{{ vars['outer_item'].user }}"
    group: "{{ vars['outer_item'].group }}"
    mode: "0750"
  when:
  - "vars['outer_item'].type == 'server'"
  - "vars['outer_item'].ccd is defined"
  - "vars['outer_item'].ccd == 'true'"
- name: openvpn | Create tls catalogs
  file:
    path: "{{ hostvars[inventory_hostname]['openvpn_' ~ item.type ~
      '_conf_dest'] ~ '/' ~ item.name ~ '/tls' }}"
    state: "directory"
    owner: "{{ item.user | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "0750"
  loop: "{{ hostvars[inventory_hostname]['openvpn'] |
    json_query(\"[].openvpn_settings[?name=='\" ~
    vars['outer_item'].name ~ \"']\") | flatten(levels=1) }}"
  loop_control:
    label: "{{ 'openvpn-' ~ item.type ~ ': ' ~ item.name }}"
