---
- name: openvpn | Gather deployment host facts
  ansible.builtin.setup:
- name: openvpn | Add the OS specific varibles
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] ~ '.yml' }}"
