---
- name: openvpn | Create OpenVPN configuration dir
  file:
    path: "{{ hostvars[inventory_hostname]['openvpn_' + item + '_conf_dest'] }}"
    state: "directory"
    group: "root"
    owner: "root"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
- name: openvpn | Create OpenVPN static pool dir
  file:
    path: "{{ hostvars[inventory_hostname]['openvpn_pool_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
  when:
  - "item == 'server'"
- name: openvpn | Create OpenVPN status dir
  file:
    path: "{{ hostvars[inventory_hostname]['openvpn_pool_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
  when:
  - "item == 'server'"
- name: openvpn | Create OpenVPN OTP counters dir
  file:
    path: "{{ hostvars[inventory_hostname]['openvpn_plugin_otp_dest'] }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
  when:
  - "item == 'server'"
