---
- name: openvpn | Create OpenVPN configuration dir
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['openvpn_' + item + '_conf_dest'] }}"
    state: "directory"
    owner: "{{ hostvars[inventory_hostname]['openvpn_user'] }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_group'] }}"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
- name: openvpn | Create OpenVPN static pool dir
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['openvpn_pool_dest'] }}"
    state: "directory"
    owner: "{{ hostvars[inventory_hostname]['openvpn_user'] }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_group'] }}"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
  when:
  - "item == 'server'"
- name: openvpn | Create OpenVPN status dir
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['openvpn_pool_dest'] }}"
    state: "directory"
    owner: "{{ hostvars[inventory_hostname]['openvpn_user'] }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_group'] }}"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
  when:
  - "item == 'server'"
- name: openvpn | Create OpenVPN OTP counters dir
  ansible.builtin.file:
    path: "{{ hostvars[inventory_hostname]['openvpn_plugin_otp_dest'] }}"
    state: "directory"
    owner: "{{ hostvars[inventory_hostname]['openvpn_user'] }}"
    group: "{{ hostvars[inventory_hostname]['openvpn_group'] }}"
    mode: "0755"
  loop: "{{ vars['openvpn_instances_types'] | flatten(levels=1) }}"
  loop_control:
    label: "{{ hostvars[inventory_hostname]['openvpn_' + item +
      '_conf_dest'] }}"
  when:
  - "item == 'server'"
