---
- name: openvpn | Gather facts about CA master
  setup:
  delegate_to: "{{ vars['openvpn_ca_storage_source']['delegate_host'] }}"
  delegate_facts: "false"
  remote_user: "{{ vars['openvpn_ca_storage_source']['delegate_user'] }}"
- name: openvpn | Check CA master facts
  assert:
    that:
    - "hostvars[inventory_hostname]['ansible_os_family'] is defined"
    msg: "Can't gather facts from CA master."
    quiet: "true"
- name: openvpn | Add the OS specific varibles
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] ~ '.yml' }}"
- name: openvpn | Set facts about CA master
  set_fact:
    local_ca_master_os: "{{
      hostvars[inventory_hostname]['ansible_os_family'] }}"
    local_packages_master: "{{
      hostvars[inventory_hostname]['openvpn_packages_master'] }}"
  delegate_to: "{{ vars['openvpn_ca_storage_source']['delegate_host'] }}"
  remote_user: "{{ vars['openvpn_ca_storage_source']['delegate_user'] }}"
- meta: "clear_facts"
