---
- name: openvpn | Gather instance facts
  setup:
- name: openvpn | Add the OS specific varibles
  include_vars: "{{
    hostvars[inventory_hostname]['ansible_os_family'] ~ '.yml' }}"
- name: openvpn | Check facter facts
  assert:
    that:
    - "hostvars[inventory_hostname]['facter_facterversion'] is defined"
    msg: "Facter facts not found. Please install facter."
- name: openvpn | Set facts about client/server instance [Facter 2]
  set_fact:
    openvpn_instance_name: "{{ hostvars[inventory_hostname]['facter_fqdn'] }}"
  when:
  - "hostvars[inventory_hostname]['facter_facterversion'].split('.')[0] <= '2'"
- name: openvpn | Set facts about client/server instance [Facter 3]
  set_fact:
    openvpn_instance_name: "{{
      hostvars[inventory_hostname]['facter_networking']['fqdn'] }}"
  when:
   - "hostvars[inventory_hostname]['facter_facterversion'].split('.')[0] > '2'"
